### ISSUE TITLE
Pytesseract deployment issue

### ISSUE THREAD

**Issue by rohankokkula** [fatalcoder524/indian-vehicle-info#2]
I've been working on pytessaract based project and want to deploy it to heroku.
I works fine with localhost but pytesseract_cmd path is not working at heroku.
Did you added any additional Buildpacks?
Can I know the process?

**Comment by fatalcoder524** [comment]
I really don't remember the guide I followed. But the buildpack link in my heroku project was [Buildpack URL](https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku-community/apt.tgz).

**Comment by rohankokkula** [comment]
Great. The problem got resolved. Thanks.!
