### ISSUE TITLE
That site is no more 

### ISSUE THREAD

**Issue by andysagar** [fatalcoder524/indian-vehicle-info#3]
That site is no more please update your code

**Comment by fatalcoder524** [comment]
The Official site from where we retrieve data is changed and they changed their logic and reduced some of the information given. Please use this as a guide to build your for the new website.

New Site: https://vahan.nic.in/nrservices/faces/user/searchstatus.xhtml

BTW remember, without the permission of the site administrator, scrapping the data and misusing is illegal. This was just created for educational purposes!
